spring:
  application:
    name: experis-shopping-cart
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      org:
        hibernate:
          envers:
            default_schema: audit
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:experis}
    password: ${DB_PASSWORD:experis_password140121}
    username: ${DB_USERNAME:worldoffice}
    hikari:
      idle-timeout: 10
  main:
    banner-mode: "off"
server:
  servlet:
    context-path: /${spring.application.name}
  port: ${PORT:8081}
  mvc:
    favicon:
      enabled: false
logging:
  level:
    ROOT: ${LOG_LEVEL_ROOT:INFO}
    com.experis: ${LOG_LEVEL_PROJECT:INFO}
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
api:
  info:
    title: Server API Services Documentation
    description: This document describes the API methods for server API operations. This document only describes the API methods intended to be used from internal systems.
    termsOfService:
    version: 1.0.0
    contact:
      url: https://www.linkedin.com/in/cesar-burgos-rodriguez-b1165293/
      name: Cesar Burgos Rodriguez
      email: cbr9303@gmail.com
    license:
      name:
      url:
  server:
    url: http://localhost:8081/${spring.application.name}
    description: Local environtment
